version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./apps/server
    volumes:
      - /apps/server/node_modules
      - ./apps/server:/app
    ports:
      - '8080:8080'

  client:
    build:
      dockerfile: Dockerfile
      context: ./apps/web
    volumes:
      - /apps/web/node_modules
      - ./apps/web:/app
    ports:
      - '3000:3000'
