version: '3'

services:
  server:
    build:
      context: ./apps/server
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development

  web:
    build:
      context: ./apps/web
    ports:
      - '3000:3000'
