version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./apps/server
    volumes:
      - /apps/server/node_modules
      - ./apps/server:/app
    ports:
      - '8080:8080'
