runtime: nodejs20

service: default
env_variables:
  SESSION_KEY: '@secret-manager/projects/geometric-rex-332309/secrets/SESSION_KEY'
  JWT_SECRET_KEY: '@secret-manager/projects/geometric-rex-332309/secrets/JWT_SECRET_KEY'
  HOST: '@secret-manager/projects/geometric-rex-332309/secrets/HOST'
  DATABASE: '@secret-manager/projects/geometric-rex-332309/secrets/DATABASE'
  DB_PORT: '@secret-manager/projects/geometric-rex-332309/secrets/DB_PORT'
  USER: '@secret-manager/projects/geometric-rex-332309/secrets/USER'
  PASSWORD: '@secret-manager/projects/geometric-rex-332309/secrets/PASSWORD'
  NODE_ENV: '@secret-manager/projects/geometric-rex-332309/secrets/NODE_ENV'
