runtime: nodejs20

service: default
env_variables:
  SESSION_KEY: SESSION_KEY
  JWT_SECRET_KEY: JWT_SECRET_KEY
  HOST: HOST
  DATABASE: DATABASE
  DB_PORT: DB_PORT
  USER: USER
  PASSWORD: PASSWORD
  NODE_ENV: NODE_ENV
