runtime: nodejs20

service: default
env_variables:
  SESSION_KEY: '@secret-manager/projects/3859690101/secrets/SESSION_KEY'
  JWT_SECRET_KEY: '@secret-manager/projects/3859690101/secrets/JWT_SECRET_KEY'
  DATABASE: '@secret-manager/projects/3859690101/secrets/DATABASE'
  DB_PORT: '@secret-manager/projects/3859690101/secrets/DB_PORT'
  DB_USER: '@secret-manager/projects/3859690101/secrets/DB_USER'
  PASSWORD: '@secret-manager/projects/3859690101/secrets/PASSWORD'
  NODE_ENV: '@secret-manager/projects/3859690101/secrets/NODE_ENV'
  DB_URI: '@secret-manager/projects/3859690101/secrets/DB_URI'
