name: Feature Pull Request CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint-format-test:
    name: Lint, Format, and Test
    runs-on: self-host
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Run linting and formatting checks
        run: pnpm lint && pnpm format

      - name: Run tests
        run: pnpm test:all

  merge-to-development:
    name: Merge to Development
    runs-on: ubuntu-latest
    needs: lint-format-test
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.base.ref == 'development'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.12.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
      - name: Handle merge conflicts
        if: steps.merge.outputs.conflicts == 'true'
        run: |
          echo "Merge conflicts occurred. Please resolve conflicts manually."
