name: Test and Merge

on:
  push:
    branches:
      - Development

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: .
        run: pnpm install

      - name: Run all the tests
        working-directory: .
        run: pnpm test:all

      - name: Run Linter
        working-directory: .
        run: pnpm lint

      - name: Run Formatter
        working-directory: .
        run: pnpm format

  merge:
    name: Merge to Development Branch
    runs-on: self-hosted
    needs: test
    if: success()

    steps:
      - name: Merge to Development Branch
        uses: actions/checkout@v3

      - name: Merge to Development
        run: git merge Development
