on:
  pull_request:
    branches:
      - master

jobs:
  lint-format-test:
    name: Testing
    runs-on: self-hosted
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linting and Formatting Checks
        run: |
          pnpm lint
          pnpm format

      - name: Run Tests
        run: pnpm test:all
