name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  push-to-artifact-registry:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Server Docker image
        working-directory: ./apps/server
        run: |
          docker build -t gcr.io/geometric-rex-332309/productionrepo/server-image:latest . \
          -e "PORT=$secrets.PORT"

      - name: Build UI Docker Image
        working-directory: ./apps/web
        run: |
          docker build -t gcr.io/geometric-rex-332309/productionrepo/ui-image:latest .

      - name: Configure Docker Client of GC Cloud
        run: |-
          gcloud auth configure-docker

      - name: Push the Image to Artifact Registry
        run: |-
          docker push gcr.io/geometric-rex-332309/productionrepo/server-image:latest
          docker push gcr.io/geometric-rex-332309/productionrepo/ui-image:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GC_SECRETS }}

      - name: Deploy with Docker Compose
        run: |
          gcloud auth configure-docker
          docker-compose -f docker-compose.prod.yaml up -d
