name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  push-to-artifact-registry:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push server Docker image
        working-directory: ./apps/server
        run: |
          docker build -t gcr.io/geometric-rex-332309/productionrepo/server-image . \
          -e "PORT=$secrets.PORT"
          docker push gcr.io/geometric-rex-332309/productionrepo/server-image

      - name: Build and push UI Docker image
        working-directory: ./apps/ui
        run: |
          docker build -t gcr.io/geometric-rex-332309/productionrepo/ui-image .
          docker push gcr.io/geometric-rex-332309/productionrepo/ui-image

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GC_SECRETS }}

      - name: Deploy with Docker Compose (assuming prod.yaml for production)
        run: |
          gcloud auth configure-docker
          docker-compose -f docker-compose.prod.yaml up -d
