name: Test and Merge

on:
  push:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install  dependencies
        working-directory: .
        run: pnpm install

      - name: Run all the tests
        working-directory: .
        run: pnpm test:all

      - name: Run Linter
        working-directory: .
        run: pnpm lint

      - name: Run Formtter
        working-directory: .
        run: pnpm format

      - name: Merge code to main branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
